name: fisrt-pipeline-on-github

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
   fisrt-job:
     runs-on: ubuntu-latest
     steps:
      - name: echo commands
        run: echo "hello world"